# Generated by Django 4.1.7 on 2023-05-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("create", "0001_initial"),
        ("create", "0002_alter_sheet_boxes"),
        ("create", "0003_alter_sheet_image_playbook_box"),
        ("create", "0004_boxposition"),
        (
            "create",
            "0005_alter_box_options_remove_box_count_remove_box_detail_and_more",
        ),
        ("create", "0006_sheet_image_height_sheet_image_width"),
        ("create", "0007_remove_sheet_boxes"),
        ("create", "0008_alter_box_options_box_sort_order"),
        ("create", "0009_alter_box_name"),
        ("create", "0010_alter_box_kind"),
        ("create", "0011_alter_box_kind"),
        ("create", "0012_playbook_sheet4_playbook_sheet5_playbook_sheet6_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="sheet_images"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
                (
                    "image_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text_field", "Text Field"),
                            ("text_box", "Text Box"),
                            ("number", "Number"),
                            ("checkbox", "Checkbox"),
                            ("move", "Move"),
                            ("overlay", "Overlay"),
                            ("checkbox_and_text_field", "Checkable Text Field"),
                            ("default_move", "Default Move"),
                            ("optional_move", "Optional Move"),
                            ("list", "List"),
                            (
                                "many_checkboxes_and_text_fields",
                                "Many Checkboxes And Text Fields",
                            ),
                            ("clear_button", "Clear Button"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.sheet",
                    ),
                ),
                (
                    "adjustable_height",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "adjustable_width",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "boxes",
                "ordering": ("group", "sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="BoxPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left", models.DecimalField(decimal_places=2, max_digits=10)),
                ("top", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.box"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.sheet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
                (
                    "sheet1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook1",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook2",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook3",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook4",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook5",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook6",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook7",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet8",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook8",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet9",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook9",
                        to="create.sheet",
                    ),
                ),
            ],
        ),
    ]
