# Generated by Django 4.1.7 on 2023-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="boxes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
