# Generated by Django 4.1.7 on 2023-03-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0002_alter_sheet_boxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="sheet_images"),
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
                (
                    "sheet1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook1",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook2",
                        to="create.sheet",
                    ),
                ),
                (
                    "sheet3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook3",
                        to="create.sheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text_field", "Text Field"),
                            ("text_box", "Text Box"),
                            ("list", "List"),
                            ("number", "Number"),
                            ("checkbox", "Checkbox"),
                            ("checkbox_and_text_field", "Checkable Text Field"),
                            (
                                "many_checkboxes_and_text_fields",
                                "Many Checkboxes And Text Fields",
                            ),
                            ("default_move", "Default Move"),
                            ("optional_move", "Optional Move"),
                            ("clear_button", "Clear Button"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=256, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.sheet",
                    ),
                ),
            ],
        ),
    ]
