# Generated by Django 4.1.7 on 2023-04-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0003_alter_sheet_image_playbook_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left", models.DecimalField(decimal_places=2, max_digits=10)),
                ("top", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.box"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.sheet"
                    ),
                ),
            ],
        ),
    ]
