# Generated by Django 4.1.7 on 2023-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0004_boxposition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={"verbose_name_plural": "boxes"},
        ),
        migrations.RemoveField(
            model_name="box",
            name="count",
        ),
        migrations.RemoveField(
            model_name="box",
            name="detail",
        ),
        migrations.AddField(
            model_name="box",
            name="adjustable_height",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="box",
            name="adjustable_width",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="box",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="box",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text_field", "Text Field"),
                    ("text_box", "Text Box"),
                    ("number", "Number"),
                    ("checkbox", "Checkbox"),
                    ("default_move", "Default Move"),
                    ("optional_move", "Optional Move"),
                    ("checkbox_and_text_field", "Checkable Text Field"),
                    ("list", "List"),
                    (
                        "many_checkboxes_and_text_fields",
                        "Many Checkboxes And Text Fields",
                    ),
                    ("clear_button", "Clear Button"),
                ],
                max_length=50,
            ),
        ),
    ]
