# Generated by Django 4.1.7 on 2023-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "create",
            "0005_alter_box_options_remove_box_count_remove_box_detail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="image_height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="sheet",
            name="image_width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
