# Generated by Django 4.1.7 on 2023-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0007_remove_sheet_boxes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={
                "ordering": ("group", "sort_order", "name"),
                "verbose_name_plural": "boxes",
            },
        ),
        migrations.AddField(
            model_name="box",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
