# Generated by Django 4.1.7 on 2023-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0008_alter_box_options_box_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
