# Generated by Django 4.1.7 on 2023-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0009_alter_box_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text_field", "Text Field"),
                    ("text_box", "Text Box"),
                    ("number", "Number"),
                    ("checkbox", "Checkbox"),
                    ("move", "Move"),
                    ("default_move", "Default Move"),
                    ("optional_move", "Optional Move"),
                    ("checkbox_and_text_field", "Checkable Text Field"),
                    ("list", "List"),
                    (
                        "many_checkboxes_and_text_fields",
                        "Many Checkboxes And Text Fields",
                    ),
                    ("clear_button", "Clear Button"),
                ],
                max_length=50,
            ),
        ),
    ]
