# Generated by Django 4.1.7 on 2023-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("create", "0013_alter_box_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbook",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
