# Generated by Django 4.1.7 on 2023-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("create", "0014_playbook_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbook",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
    ]
