# Generated by Django 4.1.7 on 2023-05-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("play", "0001_initial"),
        ("play", "0002_remove_character_sheet_character_playbook"),
        ("play", "0003_remove_character_name_alter_character_values"),
        ("play", "0004_alter_character_playbook"),
        ("play", "0005_case_person_location_casefiles"),
        ("play", "0006_alter_casefiles_options_character_image"),
        ("play", "0007_alter_casefiles_case_files_subtitle"),
        ("play", "0008_case_visible_location_visible_person_visible"),
        ("play", "0009_case_image"),
        ("play", "0010_remove_location_notes_remove_person_notes_and_more"),
        ("play", "0011_location_sort_order_person_sort_order"),
        ("play", "0012_case_open"),
        ("play", "0013_case_player_notes"),
        ("play", "0014_alter_person_image"),
        ("play", "0015_alter_person_image"),
    ]

    initial = True

    dependencies = [
        (
            "create",
            "0005_alter_box_options_remove_box_count_remove_box_detail_and_more",
        ),
        ("create", "0009_alter_box_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.play"
                    ),
                ),
                ("visible", models.BooleanField(default=False, null=True)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="people_images"),
                ),
                ("gm_notes", models.TextField(blank=True, null=True)),
                ("open", models.BooleanField(default=False, null=True)),
                ("player_notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.play"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.player"
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.playbook",
                    ),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="people_images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_files_are_called",
                    models.CharField(default="Case Files", max_length=50),
                ),
                (
                    "case_files_subtitle",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "cases_are_called",
                    models.CharField(
                        blank=True, default="Case", max_length=50, null=True
                    ),
                ),
                (
                    "people_are_called",
                    models.CharField(
                        blank=True,
                        default="Persons of Interest",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "locations_are_called",
                    models.CharField(
                        blank=True, default="Places of Note", max_length=50, null=True
                    ),
                ),
                (
                    "play",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="play.play"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "case files",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.case"
                    ),
                ),
                ("visible", models.BooleanField(default=False, null=True)),
                ("gm_notes", models.TextField(blank=True, null=True)),
                ("player_notes", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="people_images"),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.case"
                    ),
                ),
                ("visible", models.BooleanField(default=False, null=True)),
                ("gm_notes", models.TextField(blank=True, null=True)),
                ("player_notes", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
