# Generated by Django 4.1.7 on 2023-04-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "create",
            "0005_alter_box_options_remove_box_count_remove_box_detail_and_more",
        ),
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="sheet",
        ),
        migrations.AddField(
            model_name="character",
            name="playbook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="create.playbook",
            ),
        ),
    ]
