# Generated by Django 4.1.7 on 2023-04-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_remove_character_sheet_character_playbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="name",
        ),
        migrations.AlterField(
            model_name="character",
            name="values",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
