# Generated by Django 4.1.7 on 2023-04-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0009_alter_box_name"),
        ("play", "0003_remove_character_name_alter_character_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="playbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="create.playbook"
            ),
        ),
    ]
