# Generated by Django 4.1.7 on 2023-04-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0004_alter_character_playbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.play"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="people_images"),
                ),
                ("description", models.CharField(max_length=200)),
                ("notes", models.JSONField(blank=True, default=dict)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.case"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("notes", models.JSONField(blank=True, default=dict)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.case"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_files_are_called",
                    models.CharField(default="Case Files", max_length=50),
                ),
                (
                    "case_files_subtitle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cases_are_called",
                    models.CharField(
                        blank=True, default="Case", max_length=50, null=True
                    ),
                ),
                (
                    "people_are_called",
                    models.CharField(
                        blank=True,
                        default="Persons of Interest",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "locations_are_called",
                    models.CharField(
                        blank=True, default="Places of Note", max_length=50, null=True
                    ),
                ),
                (
                    "play",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="play.play"
                    ),
                ),
            ],
        ),
    ]
