# Generated by Django 4.1.7 on 2023-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0006_alter_casefiles_options_character_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casefiles",
            name="case_files_subtitle",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
