# Generated by Django 4.1.7 on 2023-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0008_case_visible_location_visible_person_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="people_images"),
        ),
    ]
