# Generated by Django 4.1.7 on 2023-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0009_case_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="person",
            name="notes",
        ),
        migrations.AddField(
            model_name="case",
            name="gm_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="gm_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="player_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gm_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="player_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
