# Generated by Django 4.1.7 on 2023-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0010_remove_location_notes_remove_person_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
