# Generated by Django 4.1.7 on 2023-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0012_case_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="player_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
