# Generated by Django 4.1.7 on 2023-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0014_alter_person_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="people_images"),
        ),
    ]
