# Generated by Django 4.1.7 on 2023-09-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0016_play_discord_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
