# Generated by Django 4.1.7 on 2023-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0017_case_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
