# Generated by Django 4.1.7 on 2023-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0018_case_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="play",
            name="gm_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
