# Generated by Django 4.1.7 on 2023-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("play", "0019_play_attachment_play_gm_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="people_images"),
        ),
        migrations.AlterField(
            model_name="case",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
        migrations.AlterField(
            model_name="play",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments"),
        ),
    ]
